# --- Settings
# Find the line with the MERIT Basins url
setting_line=$(grep -m 1 "^river_basin_shp_url" ../../0_control_files/control_active.txt) # -m 1 ensures we only return the top-most result. This is needed because variable names are sometimes used in comments in later lines

# Extract the url
shp_url=$(echo ${setting_line##*|}) # remove the part that ends at "|"
shp_url=$(echo ${shp_url%%#*}) # remove the part starting at '#'; does nothing if no '#' is present

# Find the line with the root path
setting_line=$(grep -m 1 "^root_path" ../../0_control_files/control_active.txt) # -m 1 ensures we only return the top-most result. This is needed because variable names are sometimes used in comments in later lines

# Extract the root path
root=$(echo ${setting_line##*|}) # remove the part that ends at "|"
root=$(echo ${root%%#*}) # remove the part starting at '#'; does nothing if no '#' is present

# Find the line with the domain name
setting_line=$(grep -m 1 "^domain_name" ../../0_control_files/control_active.txt) # -m 1 ensures we only return the top-most result. This is needed because variable names are sometimes used in comments in later lines

# Extract the domain name
domainname=$(echo ${setting_line##*|}) # remove the part that ends at "|"
domainname=$(echo ${domainname%%#*}) # remove the part starting at '#'; does nothing if no '#' is present

# Download catchment shapefiles and related files. 
# ---- NOTE: modify the 'pfaf number' to select a different file (e.g. cat_pfaf_71_MERIT_Hydro_v07_Basins_v01_bugfix1 ---> cat_pfaf_72_MERIT_Hydro_v07_Basins_v01_bugfix1)
for i in shp shx cpg dbf
do
wget http://hydrology.princeton.edu/data/mpan/MERIT_Basins/MERIT_Hydro_v07_Basins_v01_bugfix1/pfaf_level_02/cat_pfaf_71_MERIT_Hydro_v07_Basins_v01_bugfix1.$i
done

# Download river network shapefiles and related files. 
# ---- NOTE: modify the 'pfaf number' to select a different file (e.g. riv_pfaf_71_MERIT_Hydro_v07_Basins_v01_bugfix1 ---> riv_pfaf_72_MERIT_Hydro_v07_Basins_v01_bugfix1)
for i in shp shx cpg dbf prj
do
wget http://hydrology.princeton.edu/data/mpan/MERIT_Basins/MERIT_Hydro_v07_Basins_v01_bugfix1/pfaf_level_02/riv_pfaf_71_MERIT_Hydro_v07_Basins_v01_bugfix1.$i
done

# move the downloaded files into the appropriate subdirectory in the root folder
mv ./cat* $root/domain_$domainname/shapefiles/catchment/
mv ./riv* $root/domain_$domainname/shapefiles/river_network/

# --- Code provenance
# Generates a basic log file in the domain folder and copies the control file and itself there.
# Make a log directory if it doesn't exist
log_path="$root/domain_$domainname/shapefiles/_workflow_log/"
mkdir -p $log_path

# Log filename
today=`date '+%F'`
log_file="${today}_clone_log.txt"

# Make the log
this_file="1_download_MERIT.sh"
echo "Log generated by ${this_file} on `date '+%F %H:%M:%S'`"  > $log_path/$log_file # 1st line, store in new file
echo 'Downloaded MERIT Hydro Basins catchment and river network shapefiles.' >> $log_path/$log_file # 2nd line, append to existing file

# Copy this file to log directory
cp $this_file $log_path