#!/bin/bash

# Geospatial Dataset Processing Workflow
# Copyright (C) 2022, University of Saskatchewan
#
# This file is part of the Geospatial Dataset Processing Workflow
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This is a simple example to extract common statistics for the 
# pfaf 71 - Saskatchewan-Nelson System Shapefiles of Landsat landcover
# from the MERIT-Hydro rasters.

# Always call the script in the root directory of this repository
# cd ..
# echo "The current directory is: $(pwd)"

# --- Settings
# Find the line with the root path
setting_line=$(grep -m 1 "^root_path" ../0_control_files/control_active.txt) # -m 1 ensures we only return the top-most result. This is needed because variable names are sometimes used in comments in later lines

# Extract the root path
root=$(echo ${setting_line##*|}) # remove the part that ends at "|"
root=$(echo ${root%%#*}) # remove the part starting at '#'; does nothing if no '#' is present

# Find the line with the domain name
setting_line=$(grep -m 1 "^domain_name" ../../0_control_files/control_active.txt) # -m 1 ensures we only return the top-most result. This is needed because variable names are sometimes used in comments in later lines

# Extract the domain name
domainname=$(echo ${setting_line##*|}) # remove the part that ends at "|"
domainname=$(echo ${domainname%%#*}) # remove the part starting at '#'; does nothing if no '#' is present


# implement subsetting and zonal statistics
cd gistool
./extract-gis.sh --dataset="landsat" \
  --dataset-dir="$root/domain_$domainname/landcover/" \
  --variable="NA_NALCMS_2010_v2_land_cover_30m" \
  --shape-file="$root/domain_$domainname/shapefiles/catchment/BowAtBanff_cat.shp" \
  --print-geotiff=true \
  --output-dir="$root/domain_$domainname/parameters/zonalhist/" \
  --prefix="landsat_$domainname_" \
  --stat="majority,minority,frac" \
  --email=cooper.albano@usask.ca;
cd ../

# --- Code provenance
# Generates a basic log file in the domain folder and copies the control file and itself there.
# Make a log directory if it doesn't exist
log_path="$root/domain_$domainname/parameters/zonalhist/_workflow_log/"
mkdir -p $log_path

# Log filename
today=`date '+%F'`
log_file="${today}_clone_log.txt"

# Make the log
this_file="2_landcover_zonalhist.sh"
echo "Log generated by ${this_file} on `date '+%F %H:%M:%S'`"  > $log_path/$log_file # 1st line, store in new file
echo 'Calculated majority, minority, frac from catchment and 2010 NALCMS' >> $log_path/$log_file # 2nd line, append to existing file

# Copy this file to log directory
cp $this_file $log_path